# Generated by Django 5.0.4 on 2024-04-11 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_schedule', models.CharField(max_length=21)),
                ('actual_schedule', models.CharField(max_length=21)),
                ('week', models.IntegerField()),
                ('unique_id', models.CharField(max_length=10)),
                ('required_schedule_last_modified', models.DateTimeField()),
                ('actual_schedule_last_modified', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
