# Generated by Django 5.0.4 on 2024-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shift_delete_shiftschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='week',
            field=models.CharField(max_length=3),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
