# Generated by Django 5.0.4 on 2024-04-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_shift_week_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
