# Generated by Django 5.0.4 on 2024-05-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shift_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='week',
            field=models.IntegerField(),
        ),
    ]
