# Generated by Django 5.0.4 on 2024-07-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_shift_reserve_last_modified_shift_reserve_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='reserve_last_modified',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='reserve_shift',
        ),
        migrations.AddField(
            model_name='shift',
            name='off_days',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='reserve_days',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='work_days',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
