# Generated by Django 5.0.4 on 2024-09-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='actual_last_modified',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='application_last_modified',
        ),
        migrations.AddField(
            model_name='shift',
            name='temporary_shift',
            field=models.CharField(default=0, max_length=21),
            preserve_default=False,
        ),
    ]
