# Generated by Django 5.0.4 on 2024-09-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_shift_actual_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='application_change',
            field=models.CharField(default=0, max_length=21),
            preserve_default=False,
        ),
    ]
