# Generated by Django 5.0.4 on 2024-09-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_shift_application_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='application_change',
            new_name='change_modification',
        ),
    ]
