# Generated by Django 5.0.4 on 2024-09-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_application_change_shift_change_modification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='change_modification',
            new_name='modification',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='temporary_shift',
        ),
    ]
