# Generated by Django 5.0.4 on 2024-10-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_change_modification_shift_modification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='actual_shift',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='applied_shift',
            new_name='schedule',
        ),
    ]
