# Generated by Django 5.0.4 on 2024-10-02 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_actual_shift_shift_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shift',
            new_name='Roster',
        ),
        migrations.RenameField(
            model_name='roster',
            old_name='week',
            new_name='week_number',
        ),
    ]
