# Generated by Django 5.0.4 on 2024-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_shift_roster_rename_week_roster_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='maximum_vacation',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roster',
            name='taken_vacation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roster',
            name='vacation',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
