# Generated by Django 5.0.4 on 2024-10-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_roster_maximum_vacation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
