# Generated by Django 5.0.4 on 2024-11-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_roster_call_in_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='reserve_call_ins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
