# Generated by Django 5.0.4 on 2024-11-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_roster_reserve_call_ins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='reserve_call_ins',
        ),
        migrations.AddField(
            model_name='roster',
            name='reserve_call_in',
            field=models.BooleanField(default=False),
        ),
    ]
