# Generated by Django 5.0.4 on 2024-11-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_roster_reserve_call_ins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='call_in_reserve',
        ),
        migrations.AddField(
            model_name='roster',
            name='reserve_call_in_days',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
