from pydantic import BaseModel


class RosterUpdateInputSchema(BaseModel):
    """
    Schema for the input data required to update a roster.
    
    Attributes:
        user_input (str): The input provided by the user to update the roster.
    """
    user_input: str


class RosterUpdateOutputSchema(BaseModel):
    """
    Schema for the output data after processing a roster update.
    
    Attributes:
        agent_output (str): The response generated by the agent after processing the input.
    """
    agent_output: str


class VacationClaimInputSchema(BaseModel):
    """
    Schema for the input data required to claim vacation.

    Attributes:
        user_input (str): The input provided by the user to claim vacation.
    """
    user_input: str


class VacationRejectionInputSchema(BaseModel):
    """
    Schema for the input data required to reject a vacation claim.

    Attributes:
        user_input (str): The input provided by the user to reject a vacation claim.
    """
    user_input: str


class VacationRejectionOutputSchema(BaseModel):
    """
    Schema for the output data after rejecting a vacation claim.

    Attributes:
        agent_output (str): The response generated by the agent after rejecting the vacation claim.
    """
    agent_output: str


class VacationSicknessClaimOutputSchema(BaseModel):
    """
    Schema for the output data after processing a sickness claim.

    Attributes:
        agent_output (str): The response generated by the agent after processing the sickness claim.
    """
    agent_output: str


class ScheduleOptimizationOutputSchema(BaseModel):
    """
    Schema for the output data after optimizing the schedule.

    Attributes:
        agent_output (str): The response generated by the agent after optimizing the schedule.
    """
    agent_output: str


class SummaryOutputSchema(BaseModel):
    """
    Schema for the summary output of a process.

    Attributes:
        agent_output (str): The summary response generated by the agent.
    """
    agent_output: str


class DropModificationsOutputSchema(BaseModel):
    """
    Schema for the output data after dropping modifications from a schedule.

    Attributes:
        agent_output (str): The response generated by the agent after dropping modifications.
    """
    agent_output: str


class SaveRosterOutputSchema(BaseModel):
    """
    Schema for the output data after saving a roster.

    Attributes:
        agent_output (str): The response generated by the agent after saving the roster.
    """
    agent_output: str
